[project]
name = "adafedemarimo"
version = "0.1.0"
description = "Minimal, reusable utilities for marimo applications"
requires-python = ">=3.13"
dependencies = [
  "marimo>=0.19.4",
  "polars>=1.37.1",
  "pydantic-ai>=1.44.0",
  "rdflib>=7.5.0",
  "rdkit>=2025.9.3",
]

[dependency-groups]
dev = [
  "pre-commit>=4.5.1",
]
