[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "adafede_marimo"
version = "0.0.1"
requires-python = ">=3.13"

[project.scripts]
lotus_wikidata_explorer = "apps.lotus_wikidata_explorer:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["adafede_marimo*"]

[tool.uv]
package = true