[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "adafedemarimo"
version = "0.1.0"
description = "Minimal, reusable utilities for marimo applications"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.2",
    "polars>=1.37.1"
]

[project.scripts]
lotus_wikidata_explorer = "apps.lotus_wikidata_explorer:main"

[tool.hatch.build.targets.wheel]
packages = ["src/adafedemarimo"]

[tool.uv]
package = true