[project]
name = "marimo-adafede-deps"
version = "0.0.1"
description = "Simple dependency file"
requires-python = "==3.13.*"
dependencies = [
  "httpx>=0.28.1",
  "marimo>=0.19.2",
  "mcp>=1.25.0",
  "openai>=2.15.0",
  "polars>=1.37.1",
  "pyarrow>=22.0.0",
  "rdflib>=7.5.0",
  "rdkit>=2025.9.3",
]

[project.scripts]
lotus_wikidata_explorer = "apps.lotus_wikidata_explorer:main"

[tool.setuptools]
packages = ["apps"]
