[project]
name = "adafedemarimo"
version = "0.0.1"

[project.scripts]
lotus_wikidata_explorer = "apps.lotus_wikidata_explorer:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["adafedemarimo*"]