[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adafedemarimo"
version = "0.1.0"
description = "Minimal, reusable utilities for marimo applications"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.2",
    "polars>=1.37.1",
    "rdflib>=7.5.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true
