[project]
name = "adafedemarimo"
version = "0.1.0"
description = "Minimal, reusable utilities for marimo applications"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.4",
    "pydantic-ai >=1.43.0",
]
[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]