[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "adafedemarimo"
version = "0.1.0"
description = "Minimal, reusable utilities for marimo applications"
requires-python = ">=3.13"

[project.scripts]
lotus_wikidata_explorer = "apps.lotus_wikidata_explorer:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["adafedemarimo*"]

[tool.uv]
package = true